import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ServiceWorkerRegistration from "@/components/pwa/ServiceWorkerRegistration";
import ThemeProvider from "@/components/theme/ThemeProvider";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";

// Matches the Prisma User model's own defaults (prisma/schema.prisma:
// themeMode DARK, accentColor #38e0ff) — used for logged-out routes like
// /login and /signup, which have no user record to read a preference from.
const DEFAULT_THEME_MODE = "DARK" as const;
const DEFAULT_ACCENT_COLOR = "#38e0ff";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // ThemeProvider needs to cover the whole authenticated app (not just
  // /canvas) so /recycle-bin and the auth pages are themed too. There's no
  // user session on /login or /signup (and auth() can resolve with no user
  // at all), so this falls back to the schema's own defaults instead of
  // crashing or leaving those pages unthemed.
  let themeMode: "LIGHT" | "DARK" = DEFAULT_THEME_MODE;
  let accentColor = DEFAULT_ACCENT_COLOR;

  const session = await auth();
  if (session?.user?.id) {
    const user = await db.user.findUnique({ where: { id: session.user.id } });
    if (user) {
      themeMode = user.themeMode;
      accentColor = user.accentColor;
    }
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#0a0e14" />
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeProvider themeMode={themeMode} accentColor={accentColor}>
          {children}
        </ThemeProvider>
        <ServiceWorkerRegistration />
      </body>
    </html>
  );
}
